apiVersion: v1
kind: Pod
metadata:
  name: azure-vote-back
  labels:
    app: azure-vote-back
spec:
  containers:
  - name: redis
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    ports:
    - containerPort: 6379
